# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overseer < Formula
  desc "SSH Tunnel Manager"
  homepage "https://overseer.olrik.dev/"
  version "2.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidolrik/overseer/releases/download/v2.3.1/overseer_Darwin_x86_64.tar.gz"
      sha256 "95adb6bdbed78318a22373aba223e751f202dfc30ff424660d7ee3b4c4c66615"

      define_method(:install) do
        bin.install "overseer"

        generate_completions_from_executable(bin/"overseer", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidolrik/overseer/releases/download/v2.3.1/overseer_Darwin_arm64.tar.gz"
      sha256 "64f61963cf4bc1bc9f50e41abeec3d6c06e054d61e274b095413726356c20f1f"

      define_method(:install) do
        bin.install "overseer"

        generate_completions_from_executable(bin/"overseer", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/overseer/releases/download/v2.3.1/overseer_Linux_x86_64.tar.gz"
      sha256 "38f4e93f09d6077a23bc7711866b6b82d1c8f2f28d6320d1076fc9690bb5cd38"
      define_method(:install) do
        bin.install "overseer"

        generate_completions_from_executable(bin/"overseer", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/overseer/releases/download/v2.3.1/overseer_Linux_arm64.tar.gz"
      sha256 "899419a129dc34623e31348680decc2a61bf8886c802aad94fd81617ac2149f0"
      define_method(:install) do
        bin.install "overseer"

        generate_completions_from_executable(bin/"overseer", "completion")
      end
    end
  end

  service do
    run [opt_bin/"overseer", "daemon"]
    keep_alive true
    log_path var/"log/overseer.log"
    error_log_path var/"log/overseer.log"
  end
end
