# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overseer < Formula
  desc "SSH Tunnel Manager"
  homepage "https://overseer.olrik.dev/"
  version "2.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidolrik/overseer/releases/download/v2.6.0/overseer_Darwin_x86_64.tar.gz"
      sha256 "86eff03d4d1cda76897efe93eb97ae26150c981be84b742101af3391618ab042"

      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidolrik/overseer/releases/download/v2.6.0/overseer_Darwin_arm64.tar.gz"
      sha256 "0ef3d826647c081d082453f3795e7e47c4bda0c2f069d35989edfc1878c97800"

      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/overseer/releases/download/v2.6.0/overseer_Linux_x86_64.tar.gz"
      sha256 "b8c12dba09e2188b040e0560593e6a49e8e33758a04193cf62864555f00a66e6"
      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/overseer/releases/download/v2.6.0/overseer_Linux_arm64.tar.gz"
      sha256 "0c39a89614ee45515fedfca63a894974b065a0c866219a2b79be11ea8da05564"
      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
  end

  service do
    run [opt_bin/"overseer", "daemon"]
    keep_alive true
    log_path var/"log/overseer.log"
    error_log_path var/"log/overseer.log"
  end
end
