# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overseer < Formula
  desc "SSH Tunnel Manager"
  homepage "https://overseer.olrik.dev/"
  version "2.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidolrik/overseer/releases/download/v2.3.0/overseer_Darwin_x86_64.tar.gz"
      sha256 "071ddfe723eef5a21569af84da710c009b1cfb1f273773ff3f4bab230969c168"

      define_method(:install) do
        bin.install "overseer"

        generate_completions_from_executable(bin/"overseer", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidolrik/overseer/releases/download/v2.3.0/overseer_Darwin_arm64.tar.gz"
      sha256 "7afa9a941d0c48a31880a968edafdb2d3c32130721cddbd239ce4d170819aba5"

      define_method(:install) do
        bin.install "overseer"

        generate_completions_from_executable(bin/"overseer", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/overseer/releases/download/v2.3.0/overseer_Linux_x86_64.tar.gz"
      sha256 "46fa91ff042540b7b2daf3c1010c8e46ddba2aed8025d2696b0dffd6f0fe6fee"
      define_method(:install) do
        bin.install "overseer"

        generate_completions_from_executable(bin/"overseer", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/overseer/releases/download/v2.3.0/overseer_Linux_arm64.tar.gz"
      sha256 "ff73302864774a6cf2d43743c0a6b69b3aecc87b3b6e04e1f93c664907111f66"
      define_method(:install) do
        bin.install "overseer"

        generate_completions_from_executable(bin/"overseer", "completion")
      end
    end
  end

  service do
    run [opt_bin/"overseer", "daemon"]
    keep_alive true
    log_path var/"log/overseer.log"
    error_log_path var/"log/overseer.log"
  end
end
