# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subspace < Formula
  desc "Transparent proxy with upstream routing"
  homepage "https://subspace.olrik.dev/"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidolrik/subspace/releases/download/v0.2.0/subspace_0.2.0_darwin_amd64.tar.gz"
      sha256 "35423c4b3b8230c3a39f6a9c485260adb71a83f8e44dd00726df701fa9b589b5"

      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidolrik/subspace/releases/download/v0.2.0/subspace_0.2.0_darwin_arm64.tar.gz"
      sha256 "a2b494a740a179985b277b6053a41d605688296e4adf2abfd52aa9faff143b6c"

      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/subspace/releases/download/v0.2.0/subspace_0.2.0_linux_amd64.tar.gz"
      sha256 "1451b0e4daf9e884e9ee782d60f18d275e141123c8fb3d42eaeb085207e9c0bf"
      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/subspace/releases/download/v0.2.0/subspace_0.2.0_linux_arm64.tar.gz"
      sha256 "8cbfdab2140f4d53deeaf565dcc571eb67a89f2698dd395076d1f057f2ae1074"
      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
  end

  service do
    run [opt_bin/"subspace", "serve"]
    keep_alive true
    log_path var/"log/subspace.log"
    error_log_path var/"log/subspace.log"
  end
end
