# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subspace < Formula
  desc "Transparent proxy with upstream routing"
  homepage "https://subspace.olrik.dev/"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidolrik/subspace/releases/download/v0.1.1/subspace_0.1.1_darwin_amd64.tar.gz"
      sha256 "ccdbee52d23015abee68cc25085f96b4a6e61cb89fdaa2595dcb4603312b4728"

      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidolrik/subspace/releases/download/v0.1.1/subspace_0.1.1_darwin_arm64.tar.gz"
      sha256 "2ca9fe58b30e79ea206d23dba242be5a62e91148cca642086afdc7a033a7ac04"

      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/subspace/releases/download/v0.1.1/subspace_0.1.1_linux_amd64.tar.gz"
      sha256 "1d497166122073e75eb7c0f78f48bb42cad4638649b357ead0c314fa801dd0ae"
      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/subspace/releases/download/v0.1.1/subspace_0.1.1_linux_arm64.tar.gz"
      sha256 "49a8dc47d2e14590dda2af7f5849e81635265557e53f965e290513006d4fb283"
      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
  end

  service do
    run [opt_bin/"subspace", "serve"]
    keep_alive true
    log_path var/"log/subspace.log"
    error_log_path var/"log/subspace.log"
  end
end
