# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subspace < Formula
  desc "Transparent proxy with upstream routing"
  homepage "https://subspace.olrik.dev/"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidolrik/subspace/releases/download/v0.3.0/subspace_0.3.0_darwin_amd64.tar.gz"
      sha256 "92b3bbcc38a61eecc87bd4d5f83fa403319bc6c93f142f678dc19827b662bcaf"

      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidolrik/subspace/releases/download/v0.3.0/subspace_0.3.0_darwin_arm64.tar.gz"
      sha256 "772b74a174676abd5e0c3f348ddcb6e9f85a98b125f47c5df9144ad340e33814"

      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/subspace/releases/download/v0.3.0/subspace_0.3.0_linux_amd64.tar.gz"
      sha256 "9b0d799866e8fce343c8bb6266b0d1a9568cf9e2f1b5f986aeb8659bd462ba40"
      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/subspace/releases/download/v0.3.0/subspace_0.3.0_linux_arm64.tar.gz"
      sha256 "d6c805fce30b7439547e2d0515e902fa1041ea5c0265d173e6e19c7adae16825"
      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
  end

  service do
    run [opt_bin/"subspace", "serve"]
    keep_alive true
    log_path var/"log/subspace.log"
    error_log_path var/"log/subspace.log"
  end
end
