# This file was generated by GoReleaser. DO NOT EDIT.
cask "overseer" do
  name "overseer"
  desc "SSH Tunnel Manager"
  homepage "https://overseer.olrik.dev/"
  version "2.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "overseer"
  bash_completion "completions/overseer.bash"
  zsh_completion "completions/overseer.zsh"
  fish_completion "completions/overseer.fish"

  on_macos do
    on_intel do
      url "https://github.com/davidolrik/overseer/releases/download/v#{version}/overseer_Darwin_x86_64.tar.gz"
      sha256 "9f35e4864380bf194eb5e95e5fad3fc4b3ca8719017f66410b1cfc85249e743b"
    end
    on_arm do
      url "https://github.com/davidolrik/overseer/releases/download/v#{version}/overseer_Darwin_arm64.tar.gz"
      sha256 "2f936b0f4257d36e8b18f4137929c8bc195009c49a9208f67c34ed69d5b43c4b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/davidolrik/overseer/releases/download/v#{version}/overseer_Linux_x86_64.tar.gz"
      sha256 "1aea00b336ffe926a864f93be0bd401b5802f7d6dc5dd36e389f1d4a70d52c83"
    end
    on_arm do
      url "https://github.com/davidolrik/overseer/releases/download/v#{version}/overseer_Linux_arm64.tar.gz"
      sha256 "17f4ec338e95f0002ef37ce07d573eb4932272aa12070c12afdee83cbbda9ac3"
    end
  end

  service "run [opt_bin/"overseer", "daemon"]
keep_alive true
log_path var/"log/overseer.log"
error_log_path var/"log/overseer.log"
"

  # No zap stanza required
end
