# This file was generated by GoReleaser. DO NOT EDIT.
cask "overseer" do
  name "overseer"
  desc "SSH Tunnel Manager"
  homepage "https://overseer.olrik.dev/"
  version "2.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "overseer"
  bash_completion "completions/overseer.bash"
  zsh_completion "completions/overseer.zsh"
  fish_completion "completions/overseer.fish"

  on_macos do
    on_intel do
      url "https://github.com/davidolrik/overseer/releases/download/v#{version}/overseer_Darwin_x86_64.tar.gz"
      sha256 "7d883535b4687d88ca6867a83f3d8f1b8642e3d2fb021a13e4f51677307771ec"
    end
    on_arm do
      url "https://github.com/davidolrik/overseer/releases/download/v#{version}/overseer_Darwin_arm64.tar.gz"
      sha256 "404c64be87bc327aef8ef4a0149ba86727a4570a89bfcc8de18feb924b5443fa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/davidolrik/overseer/releases/download/v#{version}/overseer_Linux_x86_64.tar.gz"
      sha256 "dcff0152ffb9fb0e2f1b84324b71104af1179d070c8fc9fc8b9e18e8c2912092"
    end
    on_arm do
      url "https://github.com/davidolrik/overseer/releases/download/v#{version}/overseer_Linux_arm64.tar.gz"
      sha256 "5686397b1d86fcb1e7b624cfa3263414c871558100ca67a1fd5a40489b6629ad"
    end
  end

  # No zap stanza required
end
