# This file was generated by GoReleaser. DO NOT EDIT.
cask "overseer" do
  name "overseer"
  desc "SSH Tunnel Manager"
  homepage "https://overseer.olrik.dev/"
  version "2.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "overseer"
  bash_completion "completions/overseer.bash"
  zsh_completion "completions/overseer.zsh"
  fish_completion "completions/overseer.fish"

  on_macos do
    on_intel do
      url "https://github.com/davidolrik/overseer/releases/download/v#{version}/overseer_Darwin_x86_64.tar.gz"
      sha256 "30947a6e3220eecac31e415815391c613d7978fa1a49f4fcfaddf4c05e1de7f3"
    end
    on_arm do
      url "https://github.com/davidolrik/overseer/releases/download/v#{version}/overseer_Darwin_arm64.tar.gz"
      sha256 "ec10efed557ad283f97736226af8995ccc574d1d142f7bb1ec83dd0198d36427"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/davidolrik/overseer/releases/download/v#{version}/overseer_Linux_x86_64.tar.gz"
      sha256 "107b63de5040ee119d65833ecc6e187727569b0b9deb07940a2d359087c40684"
    end
    on_arm do
      url "https://github.com/davidolrik/overseer/releases/download/v#{version}/overseer_Linux_arm64.tar.gz"
      sha256 "06ab417cec9dbb917cd5822b27a083a3a063555daef8be4acb5092401560c914"
    end
  end

  service "run [opt_bin/"overseer", "daemon"]
keep_alive true
log_path var/"log/overseer.log"
error_log_path var/"log/overseer.log"
"

  # No zap stanza required
end
