# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-inspect" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "a9069c1bfe1c67d6e44ea5ac8abd51b777b82c0b5b91400426590f6478dad57a"
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v#{version}/ssh-inspect_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "61d636d3210e383d07db1bcafdcac07de1624be621d17c30d4e9b9712a77bee0"
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v#{version}/ssh-inspect_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6553fd53136c19199357c64f941cf1b16c0886274d8fdeb8bab660c5b4f34075"
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v#{version}/ssh-inspect_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "73d94051c5ef49b718d3cc121df7691bb4c44c118f5a5ac0fc994ab462c8dcc9"
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v#{version}/ssh-inspect_Linux_x86_64.tar.gz"
    end
  end

  name "ssh-inspect"
  desc "Show SSH configuration for a hostname"
  homepage "https://github.com/davidolrik/ssh-inspect"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-inspect"
  bash_completion "completions/ssh-inspect.bash"
  fish_completion "completions/ssh-inspect.fish"
  zsh_completion "completions/ssh-inspect.zsh"

  # No zap stanza required
end
