# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-inspect" do
  version "0.2.3"

  on_macos do
    on_intel do
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v#{version}/ssh-inspect_Darwin_x86_64.tar.gz"
      sha256 "9a70b4980bf50cde0247a26c086fe0266a7937c2792418f7a008c51bcce45174"
    end
    on_arm do
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v#{version}/ssh-inspect_Darwin_arm64.tar.gz"
      sha256 "c92ff6f24e45c18e61b6e8a238d5a58b1c5c6ae0d80cd9211d05e10803480eda"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v#{version}/ssh-inspect_Linux_x86_64.tar.gz"
      sha256 "6946afbf6b94d1e9f9542c63a0c0de16279e59d6dc1b213367a30409e8cb0f7d"
    end
    on_arm do
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v#{version}/ssh-inspect_Linux_arm64.tar.gz"
      sha256 "53c3dc9907a39346787db338162539cd8c3dd0282896586d09818a1d58f5eaf7"
    end
  end

  name "ssh-inspect"
  desc "Show SSH configuration for a hostname"
  homepage "https://github.com/davidolrik/ssh-inspect"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-inspect"
  bash_completion "completions/ssh-inspect.bash"
  fish_completion "completions/ssh-inspect.fish"
  zsh_completion "completions/ssh-inspect.zsh"

  # No zap stanza required

end
