# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-inspect" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "04ebe9f35a72fb578764312d150019d0553ad6de5af34cb4856a2587f1a1a3d7"
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v#{version}/ssh-inspect_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "807742cd08a19328ce9299958d4d701e1f7f9bb5c8e1ec8e773a298473b0c220"
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v#{version}/ssh-inspect_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a3cfc1e7964eab9a5ce0359546fa5cc7de5ae2e4d746ca5b780e143b72542627"
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v#{version}/ssh-inspect_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "84ef72ae9a40ddf2227036e2d5173e87d9989ba5ad5fedcd3fcecd3414c28a5a"
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v#{version}/ssh-inspect_Linux_x86_64.tar.gz"
    end
  end

  name "ssh-inspect"
  desc "Show SSH configuration for a hostname"
  homepage "https://github.com/davidolrik/ssh-inspect"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-inspect"
  bash_completion "completions/ssh-inspect.bash"
  fish_completion "completions/ssh-inspect.fish"
  zsh_completion "completions/ssh-inspect.zsh"

  # No zap stanza required
end
