# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overseer < Formula
  desc "SSH Tunnel Manager"
  homepage "https://overseer.olrik.dev/"
  version "2.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidolrik/overseer/releases/download/v2.8.1/overseer_Darwin_x86_64.tar.gz"
      sha256 "9b5231f884b6f4f57082a1df58abb4de3762ba4f5ceab5f205184c950847f395"

      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidolrik/overseer/releases/download/v2.8.1/overseer_Darwin_arm64.tar.gz"
      sha256 "be9ad0f29ca5a125e27b922af078e00f69d78d731930b807235e489012ea85fd"

      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/overseer/releases/download/v2.8.1/overseer_Linux_x86_64.tar.gz"
      sha256 "066e9dec4b113e44f851fa7d30ecb559830e4d93efa296c4a6bacc39a39aac63"
      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/overseer/releases/download/v2.8.1/overseer_Linux_arm64.tar.gz"
      sha256 "508054e4ee4df942e336dc0bc90c016cd85b8789b3e1003d072e52877c70fe2c"
      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
  end

  service do
    run [opt_bin/"overseer", "daemon"]
    keep_alive true
    log_path var/"log/overseer.log"
    error_log_path var/"log/overseer.log"
  end
end
