# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overseer < Formula
  desc "SSH Tunnel Manager"
  homepage "https://overseer.olrik.dev/"
  version "2.8.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidolrik/overseer/releases/download/v2.8.2/overseer_Darwin_x86_64.tar.gz"
      sha256 "3bf071ae4ba4d39195d77938e965ce506796d2454978634c2834a698841f99f1"

      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidolrik/overseer/releases/download/v2.8.2/overseer_Darwin_arm64.tar.gz"
      sha256 "edca632fe377d13bf913720553147ace4696d21e9a9a2b19adb970af799d317d"

      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/overseer/releases/download/v2.8.2/overseer_Linux_x86_64.tar.gz"
      sha256 "c5ae0ce646685fc5bfb58e5007caef7e3726091182d8cf7674403626470781bb"
      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/overseer/releases/download/v2.8.2/overseer_Linux_arm64.tar.gz"
      sha256 "5a59365ab27335835d265e086f673ffdf198f0eac85eb05394c2bfd3bd850252"
      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
  end

  service do
    run [opt_bin/"overseer", "daemon"]
    keep_alive true
    log_path var/"log/overseer.log"
    error_log_path var/"log/overseer.log"
  end
end
