# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overseer < Formula
  desc "SSH Tunnel Manager"
  homepage "https://overseer.olrik.dev/"
  version "2.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidolrik/overseer/releases/download/v2.8.0/overseer_Darwin_x86_64.tar.gz"
      sha256 "c3c64af9e3c44d3ad50d6bfe7cb397e650f7b2b316fd480fea4de90a15146c77"

      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidolrik/overseer/releases/download/v2.8.0/overseer_Darwin_arm64.tar.gz"
      sha256 "b7e50e70d83168e47c85fb7f8d8c29e40c536344396daf8486c1373b935ef969"

      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/overseer/releases/download/v2.8.0/overseer_Linux_x86_64.tar.gz"
      sha256 "63d8fbf6050b370b0643cfc43146549cd63d0e663676860aedfd3c26fb71a133"
      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/overseer/releases/download/v2.8.0/overseer_Linux_arm64.tar.gz"
      sha256 "07b71aeb27e974ff0f31f0eb0bfe2026aeda0bfd9dc3e33d9070c936dfde9a0d"
      define_method(:install) do
        bin.install "overseer"
        bash_completion.install "completions/overseer.bash" => "overseer"
        zsh_completion.install "completions/overseer.zsh" => "_overseer"
        fish_completion.install "completions/overseer.fish" => "overseer.fish"
      end
    end
  end

  service do
    run [opt_bin/"overseer", "daemon"]
    keep_alive true
    log_path var/"log/overseer.log"
    error_log_path var/"log/overseer.log"
  end
end
