# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshInspect < Formula
  desc "Show SSH configuration for a hostname"
  homepage "https://github.com/davidolrik/ssh-inspect"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v0.1.0/ssh-inspect_Darwin_x86_64.tar.gz"
      sha256 "3b2a2285410bb4e10d3b2b37c3664e7b25ab483a43b082f16bd2d930c475e22d"

      define_method(:install) do
        bin.install "ssh-inspect"

        generate_completions_from_executable(bin/"ssh-inspect", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v0.1.0/ssh-inspect_Darwin_arm64.tar.gz"
      sha256 "aed00c8076a1c2f1dbc2789b249b00557e2e337cfdbf22f475144eb0c9d79cca"

      define_method(:install) do
        bin.install "ssh-inspect"

        generate_completions_from_executable(bin/"ssh-inspect", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v0.1.0/ssh-inspect_Linux_x86_64.tar.gz"
      sha256 "b55c918260d0f6879a3fc41dc7e18004d67d43726a0102b578b3f48dc14cdda5"
      define_method(:install) do
        bin.install "ssh-inspect"

        generate_completions_from_executable(bin/"ssh-inspect", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/ssh-inspect/releases/download/v0.1.0/ssh-inspect_Linux_arm64.tar.gz"
      sha256 "7f372d25d5beefd6dc98cf2786247975b3020c64b8554bec1ec899263be88f14"
      define_method(:install) do
        bin.install "ssh-inspect"

        generate_completions_from_executable(bin/"ssh-inspect", "completion")
      end
    end
  end
end
