# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subspace < Formula
  desc "Transparent proxy with upstream routing"
  homepage "https://subspace.olrik.dev/"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidolrik/subspace/releases/download/v1.8.0/subspace_1.8.0_darwin_amd64.tar.gz"
      sha256 "0fe1799e20171b3ed181a1c20fc303dad0e419dd8af431640c64ff51c4703864"

      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidolrik/subspace/releases/download/v1.8.0/subspace_1.8.0_darwin_arm64.tar.gz"
      sha256 "01678d51e51ff3d023389130e057f761194b8bbfa57d5599be12058bb5afbc70"

      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/subspace/releases/download/v1.8.0/subspace_1.8.0_linux_amd64.tar.gz"
      sha256 "ec72e3d5db03aa33298a155694c0f547352390cd26fc7f972907d6223c719a83"
      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/subspace/releases/download/v1.8.0/subspace_1.8.0_linux_arm64.tar.gz"
      sha256 "4d5759dfe795fab9c92ffc597172bbd85e3821fd3c0da5da37fe9666aa64655d"
      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
  end

  service do
    run [opt_bin/"subspace", "serve"]
    keep_alive true
    log_path var/"log/subspace.log"
    error_log_path var/"log/subspace.log"
  end
end
