# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subspace < Formula
  desc "Transparent proxy with upstream routing"
  homepage "https://subspace.olrik.dev/"
  version "1.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidolrik/subspace/releases/download/v1.11.0/subspace_1.11.0_darwin_amd64.tar.gz"
      sha256 "9a8ae6cc3120eb5703c6b4f39b3edd22ef56e334f0fddfe2a8d1415f8332053e"

      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidolrik/subspace/releases/download/v1.11.0/subspace_1.11.0_darwin_arm64.tar.gz"
      sha256 "4977c4fa04bfc72df4c7048ba7be53979248d14753dda78424a9b8bfd3312ae8"

      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/subspace/releases/download/v1.11.0/subspace_1.11.0_linux_amd64.tar.gz"
      sha256 "b53b08885474cd0a56df88adc26e92bfbde244398142d69a34cfad2f506a3118"
      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/subspace/releases/download/v1.11.0/subspace_1.11.0_linux_arm64.tar.gz"
      sha256 "5ef181f7f60c7c13be8da7b46cee8c45d1a29c78841f27347e2d69deaa5a9f10"
      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
  end

  service do
    run [opt_bin/"subspace", "serve"]
    keep_alive true
    log_path var/"log/subspace.log"
    error_log_path var/"log/subspace.log"
  end
end
