# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subspace < Formula
  desc "Transparent proxy with upstream routing"
  homepage "https://subspace.olrik.dev/"
  version "1.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidolrik/subspace/releases/download/v1.10.0/subspace_1.10.0_darwin_amd64.tar.gz"
      sha256 "242ff09edf62426b93960c8598db9c942bf965aadfe179fd62bea7eaf0cfff61"

      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidolrik/subspace/releases/download/v1.10.0/subspace_1.10.0_darwin_arm64.tar.gz"
      sha256 "e9855777e91410b1c97c88cd720ecf9a5bce021227792b12d4ad10217b8bcf18"

      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/subspace/releases/download/v1.10.0/subspace_1.10.0_linux_amd64.tar.gz"
      sha256 "7bc0ee2426ed101b0b2f15935d3e3f9f719b4f49ea1bf539cd9ae4e45a8cd458"
      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidolrik/subspace/releases/download/v1.10.0/subspace_1.10.0_linux_arm64.tar.gz"
      sha256 "1e8d6bc515e8da5620f2cab69538acf1e88996930d2f04c5718820ff56cf356d"
      define_method(:install) do
        bin.install "subspace"

        generate_completions_from_executable(bin/"subspace", "completion")
      end
    end
  end

  service do
    run [opt_bin/"subspace", "serve"]
    keep_alive true
    log_path var/"log/subspace.log"
    error_log_path var/"log/subspace.log"
  end
end
